name: Build Release Artifacts

on:
  workflow_dispatch:
  pull_request:
    branches:
      - 'releases/**'

jobs:
  build-artifacts:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NEXUS_MAVEN_RELEASE_URL: ${{ vars.NEXUS_MAVEN_RELEASE_URL }}
      NEXUS_MAVEN_USERNAME: ${{ vars.NEXUS_MAVEN_USERNAME }}
      NEXUS_MAVEN_PASSWORD: ${{ secrets.NEXUS_MAVEN_PASSWORD }}
    steps:
      - uses: actions/checkout@v4.1.1

      - name: Set up JDK 11
        uses: actions/setup-java@v4.1.0
        with:
          java-version: 11
          distribution: temurin
          cache: gradle

      - name: Perform gradle build
        run: |
          ./gradlew firebasePublish -Durl="$NEXUS_MAVEN_RELEASE_URL" -Dusername="$NEXUS_MAVEN_USERNAME" -Dpassword="$NEXUS_MAVEN_PASSWORD"

      - name: Upload generated artifacts
        uses: actions/upload-artifact@v4.3.3
        with:
          name: release_artifacts
          path: build/*.zip
          retention-days: 15
